services:
  backend-service:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: backend-service
    ports:
      - "8080:8080"
    networks:
      - default

networks:
  default:
    name: backend-service

volumes:
  mysql-data:
