input{
    tcp{
        # Socket port
        port => 5600
        codec => json
    }
}

output{
    elasticsearch{
    hosts => ["http://elastic-search:9200"]
    index => "elk-index-%{appName}"
    }
}