server:
    port: 8080

spring:
    application:
        name: backend-service
    profiles:
        active: @spring.profiles.active@

management:
  endpoints:
    web:
      exposure:
        include: health, info

logging:
    level:
        root: INFO
