spring:
    application:
        name: backend-service
    profiles:
        active: @spring.profiles.active@
    flyway:
        enabled: true
        locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health, info

logging:
    level:
        root: INFO
