spring:
    config:
        activate:
            on-profile: prod

    devtools:
        add-properties: true

    datasource:
        url: ${POSTGRES_PROD_URL}
        username: ${POSTGRES_PROD_USER}
        password: ${POSTGRES_PROD_PASSWORD}

    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: false
        properties:
            hibernate:
                format_sql: false

    springdoc:
        enabled: false
        swagger-ui:
            enabled: false
