spring:
    config:
        activate:
            on-profile: prod

    datasource:
        url: ${POSTGRES_PROD_URL}
        username: ${POSTGRES_PROD_USER}
        password: ${POSTGRES_PROD_PASSWORD}

    jpa:
        hibernate:
            # Chỉ validate schema
            ddl-auto: validate

        # Không log SQL ở production
        show-sql: false

        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: false

    flyway:
        enabled: true
        locations: classpath:db/migration

        # Chỉ bật nếu migrate DB cũ sang Flyway
        baseline-on-migrate: true

        # Chặn clean production DB
        clean-disabled: true

    springdoc:
        enabled: false

        swagger-ui:
            enabled: false

server:
    error:
        include-message: always
        include-stacktrace: always
