server:
    port: ${DEV_SERVER_PORT}
    error:
        include-message: always
        include-stacktrace: always

spring:
    config:
        activate:
            on-profile: dev

    devtools:
        add-properties: true

    datasource:
        url: ${DEV_POSTGRES_URL}
        username: ${DEV_POSTGRES_USERNAME}
        password: ${DEV_POSTGRES_PASSWORD}

    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: true

        properties:
            hibernate:
                format_sql: true

    sendgrid:
        api-key: ${SENDGRID_API_KEY}
        sender-email: ${SENDGRID_SENDER_EMAIL}

    flyway:
        enabled: true
        locations: classpath:db/migration
        baseline-on-migrate: true

    jwt:
        expire-minutes: ${JWT_EXPIRATION_MINUTES}
        expire-days: ${JWT_EXPIRATION_DAYS}
        access-secret-key: ${JWT_ACCESS_SECRET_KEY}
        refresh-secret-key: ${JWT_REFRESH_SECRET_KEY}

    springdoc:
        api-docs:
            path: /v3/api-docs
        enabled: true

        swagger-ui:
            enabled: true

openapi:
    service:
        api-docs: v3/api-docs
        title: Backend Service API Document for Development
        description: API documentation for Backend Service
        version: 1.0.0
        server: http://localhost:${server.port}
