server:
    port: ${PROD_SERVER_PORT}
    error:
        include-message: never
        include-stacktrace: never

spring:
    config:
        activate:
            on-profile: test

    devtools:
        add-properties: true

    datasource:
        url: ${POSTGRES_TEST_URL}
        username: ${POSTGRES_TEST_USER}
        password: ${POSTGRES_TEST_PASSWORD}

    jpa:
        hibernate:
            ddl-auto: validate

        show-sql: true

        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true

    flyway:
        enabled: true
        locations: classpath:db/migration
        baseline-on-migrate: true

    jwt:
        expire:
            minutes: ${JWT_EXPIRATION_MINUTES}
            days: ${JWT_EXPIRATION_DAYS}

        access-secret-key: ${JWT_ACCESS_SECRET_KEY}

        refresh-secret-key: ${JWT_REFRESH_SECRET_KEY}

    springdoc:
        api-docs:
            enabled: true

        swagger-ui:
            enabled: true

openapi:
    service:
        api-docs: v3/api-docs
        title: Backend Service API Document for Testing
        description: API documentation for Backend Service
        version: 1.0.0
        server: ${BACKEND_SERVICE:http://localhost:${server.port}}
