spring:
    application:
        name: backend-service
    profiles:
        active: ${SPRING_PROFILES_ACTIVE:dev}
    flyway:
        enabled: true
        locations: classpath:db/migration

management:
    endpoints:
        web:
            exposure:
                include: health, info, prometheus

    tracing:
        sampling:
            probability: 1.0

    endpoint:
        health:
            show-details: never

    zipkin:
        tracing:
            endpoint: ${ZIPKIN_HOST:http://localhost:9411}/api/v2/spans

logging:
    level:
        root: INFO
