spring:
    config:
        activate:
            on-profile: test

    devtools:
        add-properties: true

    datasource:
        url: ${POSTGRES_TEST_URL}
        username: ${POSTGRES_TEST_USER}
        password: ${POSTGRES_TEST_PASSWORD}

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true

    springdoc:
        api-docs:
            enabled: true
        swagger-ui:
            enabled: true

openapi:
    service:
        api-docs: v3/api-docs
        title: Backend Service API Document for Testing
        description: API documentation for Backend Service
        version: 1.0.0
        server: ${BACKEND_SERVICE:http://localhost:${server.port}}
